name: Build

on:
  push:
    branches:
    - main
    - '!master'
  pull_request:
    branches:
    - main
    - '!master'

permissions:
  contents: write
  
jobs:
  checkout_and_build:
    runs-on: ubuntu-latest
    outputs:
      build_tag: ${{steps.latest_tag.outputs.tag}}
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
        with:
         fetch-tags: true
         fetch-depth: 0
      - name: list files
        run: |
          ls -al
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: get latest tag
        id: latest_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag: $latest_tag"

          if [ -z "$latest_tag" ]; then
            new_version="v0.0.1"
          else
            version=${latest_tag#v}
            IFS='.' read -r major minor patch <<< "$version"
            patch=$((patch + 1))
            new_version="$major.$minor.$patch"
          fi

          echo "New tag: $new_version"
          echo "tag=$new_version" >> $GITHUB_OUTPUT

          git tag "$new_version"
          git push origin "$new_version"
      - name: docker build
        run: |
          docker build -t microservice:${{steps.latest_tag.outputs.tag}} ./microservice/
          docker image ls
  
